### ISSUE TITLE
Remove ' is more efficient than " for strings

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [RubyLearning/rubylearning.github.io#6]
http://rubylearning.com/satishtalim/first_ruby_program.html

**Comment by kotp** [comment]
Or change to "Single quotes are more efficient than double quotes".  Because it can be difficult to see that it is not some kind of errant writing.

**Comment by prathamesh-sonpatki** [comment]
I meant to say that are single quotes really efficient over double quotes? I was thinking about just removing the whole sentence.

**Comment by IndianGuru** [comment]
Removed the sentence.
