### ISSUE TITLE
Update keywords link to latest

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [RubyLearning/rubylearning.github.io#8]
Replace http://www.ruby-doc.org/docs/keywords/1.9/
with
http://ruby-doc.org/core-2.2.0/doc/keywords_rdoc.html
on http://rubylearning.com/satishtalim/features.html

**Comment by kotp** [comment]
Coincidentally, the new list is missing `__END__` but it was missing it initially in the 1.9 documentation as well.

**Comment by IndianGuru** [comment]
Done
