### ISSUE TITLE
Remove reference to 1.9 about passing splat argument as middle argument, it works in Ruby 2 too

### ISSUE THREAD

**Issue by prathamesh-sonpatki** [RubyLearning/rubylearning.github.io#9]
http://rubylearning.com/satishtalim/writing_own_ruby_methods.html

**Comment by kotp** [comment]
This is actually a bit more complicated, as with the introduction of the named arguments, the splat argument must not be after the named arguments in the list.  But we should remove all references to Ruby 1.9 anywhere in the document, as it has been end of life for the last 10 months.

**Comment by IndianGuru** [comment]
Done on this page

**Comment by prathamesh-sonpatki** [comment]
:+1:
